#pragma once
#include <Windows.h>
#include <iostream>
#include <vector>
#include <TlHelp32.h>
#include <thread>
#include <string>
#include <time.h>
#include <cmath>
#include <filesystem>
#include <codecvt>
#include <cassert>
#include <locale>

#include "xor.hpp"
#include "driver.hpp"
#include "glob.hpp"
#include "Vector.hpp"

///	SDK
#include "Bone.hpp"
#include "Camera.hpp"
#include "profile.hpp"
#include "world.hpp"
#include "Extraction.hpp"
#include "GOM.hpp"
#include "loot.hpp"
#include "mono.hpp"
#include "movement.hpp"
#include "Physical.hpp"
#include "Player.hpp"
#include "weapon.hpp"